server {
    listen 8080;
    server_name localhost;
    
    error_page 404 /404.html;
    client_max_body_size 10M;
    
    location / {
        root ./www;
        index index.html;
        allowed_methods GET POST HEAD;
        autoindex on;
    }
    
    location /uploads/ {
        root ./www;
        allowed_methods POST HEAD;
        upload_store ./www/uploads/tmp/;
        client_max_body_size 50M;
        autoindex off;
    }
    
    location /files/ {
        root ./www;
        allowed_methods GET DELETE HEAD;
        autoindex on;
        index;
    }
}
